//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotCor
{
    public partial class MembershipReceipt
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblRoyaltyNumber;
        protected global::System.Web.UI.WebControls.Image imgMemberPhoto;
        protected global::System.Web.UI.WebControls.Label lblMemberID;
        protected global::System.Web.UI.WebControls.Label lblFullName;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.Label lblContact;
        protected global::System.Web.UI.WebControls.Label lblAddress;
        protected global::System.Web.UI.WebControls.Label lblDateJoined;
        protected global::System.Web.UI.WebControls.Label lblFee;
        protected global::System.Web.UI.WebControls.Label lblPaymentMethod;
        protected global::System.Web.UI.WebControls.Label lblAmountPaid;
        protected global::System.Web.UI.WebControls.Label lblChange;
        protected global::System.Web.UI.WebControls.Button btnPrint;
        protected global::System.Web.UI.WebControls.Button btnHome;
    }
}
