//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotCor
{
    public partial class Order
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton lnkProfile;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.TextBox txtContact;
        protected global::System.Web.UI.WebControls.TextBox txtRoyaltyNo;
        protected global::System.Web.UI.WebControls.Button btnValidate;
        protected global::System.Web.UI.WebControls.Label lblRoyaltyMsg;
        protected global::System.Web.UI.WebControls.HiddenField hdnIsRoyalty;
        
        // French Fries controls
        protected global::System.Web.UI.WebControls.Label lblStockFries;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesRegular;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesLarge;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesJumbo;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesMega;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesGiga;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesTerra;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesSourCream;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesBBQ;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesCheese;
        protected global::System.Web.UI.WebControls.RadioButton rbFriesSalt;
        protected global::System.Web.UI.WebControls.Button btnFriesMinus;
        protected global::System.Web.UI.WebControls.Label lblFriesQty;
        protected global::System.Web.UI.WebControls.Button btnFriesPlus;
        protected global::System.Web.UI.WebControls.HiddenField hdnFriesQty;
        protected global::System.Web.UI.WebControls.Button btnAddFries;
        
        // Chicken Pops controls
        protected global::System.Web.UI.WebControls.Label lblStockChicken;
        protected global::System.Web.UI.WebControls.RadioButton rbChickenSolo;
        protected global::System.Web.UI.WebControls.RadioButton rbChickenLarge;
        protected global::System.Web.UI.WebControls.RadioButton rbChickenMega;
        protected global::System.Web.UI.WebControls.RadioButton rbChickenSourCream;
        protected global::System.Web.UI.WebControls.RadioButton rbChickenBBQ;
        protected global::System.Web.UI.WebControls.RadioButton rbChickenCheese;
        protected global::System.Web.UI.WebControls.RadioButton rbChickenSalt;
        protected global::System.Web.UI.WebControls.Button btnChickenMinus;
        protected global::System.Web.UI.WebControls.Label lblChickenQty;
        protected global::System.Web.UI.WebControls.Button btnChickenPlus;
        protected global::System.Web.UI.WebControls.HiddenField hdnChickenQty;
        protected global::System.Web.UI.WebControls.Button btnAddChicken;
        
        // Loopys controls
        protected global::System.Web.UI.WebControls.Label lblStockLoopys;
        protected global::System.Web.UI.WebControls.RadioButton rbLoopysLarge;
        protected global::System.Web.UI.WebControls.RadioButton rbLoopysMega;
        protected global::System.Web.UI.WebControls.RadioButton rbLoopysSourCream;
        protected global::System.Web.UI.WebControls.RadioButton rbLoopysBBQ;
        protected global::System.Web.UI.WebControls.RadioButton rbLoopysCheese;
        protected global::System.Web.UI.WebControls.RadioButton rbLoopysSalt;
        protected global::System.Web.UI.WebControls.Button btnLoopysMinus;
        protected global::System.Web.UI.WebControls.Label lblLoopysQty;
        protected global::System.Web.UI.WebControls.Button btnLoopysPlus;
        protected global::System.Web.UI.WebControls.HiddenField hdnLoopysQty;
        protected global::System.Web.UI.WebControls.Button btnAddLoopys;
        
        // Cart controls
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCart;
        protected global::System.Web.UI.WebControls.Panel pnlCart;
        protected global::System.Web.UI.WebControls.Repeater rptCart;
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        protected global::System.Web.UI.WebControls.Label lblDiscount;
        protected global::System.Web.UI.WebControls.Label lblDeliveryFee;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        
        // Delivery and Payment controls
        protected global::System.Web.UI.WebControls.Button btnWalkIn;
        protected global::System.Web.UI.WebControls.Button btnDelivery;
        protected global::System.Web.UI.WebControls.HiddenField hdnDeliveryType;
        protected global::System.Web.UI.WebControls.Button btnGoTyme;
        protected global::System.Web.UI.WebControls.Button btnMayaBank;
        protected global::System.Web.UI.WebControls.Button btnGCash;
        protected global::System.Web.UI.WebControls.Button btnPoints;
        protected global::System.Web.UI.WebControls.HiddenField hdnPaymentMethod;
        protected global::System.Web.UI.WebControls.TextBox txtAmountPaid;
        
        protected global::System.Web.UI.WebControls.Label lblErrorMsg;
        protected global::System.Web.UI.WebControls.Button btnConfirm;
    }
}
