//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotCor
{
    public partial class Receipt
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblOrderNo;
        protected global::System.Web.UI.WebControls.Label lblOrderDate;
        protected global::System.Web.UI.WebControls.Label lblName;
        protected global::System.Web.UI.WebControls.Label lblAddress;
        protected global::System.Web.UI.WebControls.Label lblContact;
        protected global::System.Web.UI.WebControls.Label lblDelivery;
        protected global::System.Web.UI.WebControls.Panel pnlRoyalty;
        protected global::System.Web.UI.WebControls.Label lblRoyaltyNo;
        protected global::System.Web.UI.WebControls.Panel pnlNoRoyalty;
        protected global::System.Web.UI.WebControls.Repeater rptItems;
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        protected global::System.Web.UI.WebControls.Label lblDiscount;
        protected global::System.Web.UI.WebControls.Label lblDeliveryFee;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Label lblPaymentMethod;
        protected global::System.Web.UI.WebControls.Label lblAmountPaid;
        protected global::System.Web.UI.WebControls.Label lblChange;
        protected global::System.Web.UI.WebControls.Label lblPointsEarned;
        protected global::System.Web.UI.WebControls.Button btnHome;
    }
}
