//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotCor
{
    public partial class RegisterForm
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtContact;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.TextBox txtBirthDate;
        protected global::System.Web.UI.WebControls.FileUpload fileUploadPicture;
        protected global::System.Web.UI.WebControls.Button btnGoTyme;
        protected global::System.Web.UI.WebControls.Button btnMayaBank;
        protected global::System.Web.UI.WebControls.Button btnGCash;
        protected global::System.Web.UI.WebControls.Button btnPoints;
        protected global::System.Web.UI.WebControls.HiddenField hdnPaymentMethod;
        protected global::System.Web.UI.WebControls.TextBox txtAmountPaid;
        protected global::System.Web.UI.WebControls.Button btnRegister;
    }
}
